add nfs tests

diff --git a/library/common-test/tests/addons/autoperms_test.yaml b/library/common-test/tests/addons/autoperms_test.yaml
--- a/library/common-test/tests/addons/autoperms_test.yaml
+++ b/library/common-test/tests/addons/autoperms_test.yaml
@@ -77,6 +77,14 @@ tests:
             chmod: 770
             recursive: true
           mountPath: /test8
+        test9:
+          enabled: true
+          type: nfs
+          server: 1.1.1.1
+          path: /share
+          autoPermissions:
+            chown: true
+          mountPath: /test9
     asserts:
       - documentIndex: &jobDoc 0
         isKind:
@@ -152,6 +160,14 @@ tests:
         contains:
           path: spec.template.spec.volumes
           content:
+            name: test9
+            nfs:
+              server: 1.1.1.1
+              path: /share
+      - documentIndex: *jobDoc
+        contains:
+          path: spec.template.spec.volumes
+          content:
             name: tmp
             emptyDir: {}
       - documentIndex: *jobDoc
@@ -202,6 +218,13 @@ tests:
           content:
             name: test8
             mountPath: /mounts/test8
+            readOnly: false
+      - documentIndex: *jobDoc
+        contains:
+          path: spec.template.spec.containers[0].volumeMounts
+          content:
+            name: test9
+            mountPath: /mounts/test9
             readOnly: false
       - documentIndex: *jobDoc
         contains:
@@ -303,6 +326,13 @@ tests:
                   echo "Ownership before: [$before]"
                   echo "Ownership after: [$(stat -c "%u:%g" /mounts/test8)]"
                   echo ""
+                  echo "Automatically correcting ownership for /mounts/test9..."
+                  before=$(stat -c "%u:%g" /mounts/test9)
+                      chown  -f :568 /mounts/test9 || echo "Failed setting ownership using chown..."
+
+                  echo "Ownership before: [$before]"
+                  echo "Ownership after: [$(stat -c "%u:%g" /mounts/test9)]"
+                  echo ""
               echo "Finished auto permissions job..."
 
   - it: should render permissions job in ixChartContext
@@ -382,6 +412,14 @@ tests:
             chmod: 770
             recursive: true
           mountPath: /test8
+        test9:
+          enabled: true
+          type: nfs
+          server: 1.1.1.1
+          path: /share
+          autoPermissions:
+            chown: true
+          mountPath: /test9
     asserts:
       - documentIndex: *jobDoc
         isKind:
@@ -457,6 +495,14 @@ tests:
         contains:
           path: spec.template.spec.volumes
           content:
+            name: test9
+            nfs:
+              server: 1.1.1.1
+              path: /share
+      - documentIndex: *jobDoc
+        contains:
+          path: spec.template.spec.volumes
+          content:
             name: tmp
             emptyDir: {}
       - documentIndex: *jobDoc
@@ -514,6 +560,13 @@ tests:
           content:
             name: tmp
             mountPath: /tmp
+            readOnly: false
+      - documentIndex: *jobDoc
+        contains:
+          path: spec.template.spec.containers[0].volumeMounts
+          content:
+            name: test9
+            mountPath: /mounts/test9
             readOnly: false
       - documentIndex: *jobDoc
         equal:
@@ -608,6 +661,13 @@ tests:
                   echo "Ownership before: [$before]"
                   echo "Ownership after: [$(stat -c "%u:%g" /mounts/test8)]"
                   echo ""
+                  echo "Automatically correcting ownership for /mounts/test9..."
+                  before=$(stat -c "%u:%g" /mounts/test9)
+                      /usr/sbin/nfs4xdr_winacl -a chown -G 568  -c "/mounts/test9" -p "/mounts/test9" || echo "Failed setting ownership using winacl..."
+
+                  echo "Ownership before: [$before]"
+                  echo "Ownership after: [$(stat -c "%u:%g" /mounts/test9)]"
+                  echo ""
               echo "Finished auto permissions job..."
 
 # Failures
@@ -627,7 +687,7 @@ tests:
             chown: true
     asserts:
       - failedTemplate:
-          errorMessage: Auto Permissions - Allowed persistent types for auto permissions are [hostPath, pvc, emptyDir], but got [device] on [test]
+          errorMessage: Auto Permissions - Allowed persistent types for auto permissions are [hostPath, pvc, emptyDir, nfs, ixVolume], but got [device] on [test]
 
   - it: should fail trying to set permissions on readOnly
     set:
