add init containers

diff --git a/library/common/values.yaml b/library/common/values.yaml
--- a/library/common/values.yaml
+++ b/library/common/values.yaml
@@ -156,12 +156,294 @@ workload:
               enabled: true
               type: http
               port: "{{ .Values.service.main.ports.main.port }}"
-    #       # TODO: Currently implementing
-    #   initContainers:
-    #     init-cont-name:
-    #       enabled: false
-    #       type: install
-    #       # ...containerSpec
+      initContainers:
+        auto-permissions:
+          enabled: '{{ if or ( eq ( include "tc.v1.common.lib.util.autoperms.detect" $ ) "true" ) ( and ( .Values.addons.vpn.configFile.enabled ) ( ne .Values.addons.vpn.type "disabled" ) ( ne .Values.addons.vpn.type "tailscale" ) ) }}true{{ else }}false{{ end }}'
+          type: "init"
+          imageSelector: alpineImage
+          securityContext:
+            runAsUser: 0
+            runAsNonRoot: false
+          resources:
+            inherit: true
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/sh <<'EOF'
+              echo "Automatically correcting permissions..."
+              {{- $hostPathMounts := dict -}}
+              {{- range $name, $mount := .Values.persistence -}}
+                {{- if and $mount.enabled $mount.setPermissions -}}
+                  {{- $name = default ( $name| toString ) $mount.name -}}
+                  {{- $_ := set $hostPathMounts $name $mount -}}
+                {{- end -}}
+              {{- end }}
+              {{- if and ( .Values.addons.vpn.configFile.enabled ) ( ne .Values.addons.vpn.type "disabled" ) ( ne .Values.addons.vpn.type "tailscale" ) }}
+              echo "Automatically correcting permissions for vpn config file..."
+              /usr/sbin/nfs4xdr_winacl -a chown -O 568 -G 568 -c /vpn/vpn.conf -p /vpn/vpn.conf || echo "Failed setting permissions..."
+              {{- end }}
+              {{- range $_, $hpm := $hostPathMounts }}
+              echo "Automatically correcting permissions for {{ $hpm.mountPath }}..."
+              /usr/sbin/nfs4xdr_winacl -a chown -G {{ $.Values.podSecurityContext.fsGroup | default $.Values.global.defaults.podSecurityContext.fsGroup }} -r -c {{ tpl $hpm.mountPath $ | squote }} -p {{ tpl $hpm.mountPath $ | squote }} || echo "Failed setting permissions..."
+              {{- end }}
+              EOF
+          volumeMounts:
+            - inherit: "setPermissions"
+        redis-wait:
+          enabled: "{{ if .Values.redis.enabled }}true{{ else }}false{{ end }}"
+          type: "init"
+          imageSelector: redisClientImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          env:
+            REDIS_HOST:
+              secretKeyRef:
+                name: rediscreds
+                key: plainhost
+            REDIS_PASSWORD:
+              secretKeyRef:
+                name: rediscreds
+                key: redis-password
+            REDIS_PORT:
+              value: "6379"
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/bash <<'EOF'
+              echo "Executing DB waits..."
+              [[ -n "$REDIS_PASSWORD" ]] && export REDISCLI_AUTH="$REDIS_PASSWORD";
+              export LIVE=false;
+              until "$LIVE";
+              do
+                response=$(
+                    timeout -s 3 2 \
+                    redis-cli \
+                      -h "$REDIS_HOST" \
+                      -p "$REDIS_PORT" \
+                      ping
+                  )
+                if [ "$response" == "PONG" ] || [ "$response" == "LOADING Redis is loading the dataset in memory" ]; then
+                  LIVE=true
+                  echo "$response"
+                  echo "Redis Responded, ending initcontainer and starting main container(s)..."
+                else
+                  echo "$response"
+                  echo "Redis not responding... Sleeping for 10 sec..."
+                  sleep 10
+                fi;
+              done
+              EOF
+        mariadb-wait:
+          enabled: "{{ if .Values.mariadb.enabled  }}true{{ else }}false{{end}}"
+          type: "init"
+          imageSelector: mariadbClientImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          env:
+            MARIADB_HOST:
+              secretKeyRef:
+                name: mariadbcreds
+                key: plainhost
+            MARIADB_ROOT_PASSWORD:
+              secretKeyRef:
+                name: mariadbcreds
+                key: mariadb-root-password
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/bash <<'EOF'
+              echo "Executing DB waits..."
+              until
+                mysqladmin -uroot -h"${MARIADB_HOST}" -p"${MARIADB_ROOT_PASSWORD}" ping \
+                && mysqladmin -uroot -h"${MARIADB_HOST}" -p"${MARIADB_ROOT_PASSWORD}" status;
+                do sleep 2;
+              done
+              EOF
+        mongodb-wait:
+          enabled: "{{ if .Values.mongodb.enabled }}true{{ else }}false{{end}}"
+          type: "init"
+          imageSelector: mongodbClientImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          env:
+            MONGODB_HOST:
+              secretKeyRef:
+                name: mongodbcreds
+                key: plainhost
+            MONGODB_DATABASE:
+              value: "{{ .Values.mongodb.mongodbDatabase }}"
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/bash <<'EOF'
+              echo "Executing DB waits..."
+              until
+                HOME=/config && echo "db.runCommand(\"ping\")" | mongosh --host ${MONGODB_HOST} --port 27017 ${MONGODB_DATABASE} --quiet;
+                do sleep 2;
+              done
+              EOF
+        clickhouse-wait:
+          enabled: "{{ if .Values.clickhouse.enabled }}true{{ else }}false{{end}}"
+          type: "init"
+          imageSelector: alpineImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          env:
+            CLICKHOUSE_PING:
+              secretKeyRef:
+                name: clickhousecreds
+                key: ping
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/bash <<'EOF'
+              echo "Executing DB waits..."
+              until wget --quiet --tries=1 --spider "${CLICKHOUSE_PING}"; do
+                echo "ClickHouse - no response. Sleeping 2 seconds..."
+                sleep 2
+              done
+              echo "ClickHouse - accepting connections"
+              EOF
+        solr-wait:
+          enabled: "{{ if .Values.solr.enabled }}true{{ else }}false{{end}}"
+          type: "init"
+          imageSelector: wgetImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          env:
+            SOLR_HOST:
+              secretKeyRef:
+                name: solrcreds
+                key: plainhost
+            SOLR_CORES:
+              value: "{{ .Values.solr.solrCores }}"
+            SOLR_ENABLE_AUTHENTICATION:
+              value: "{{ .Values.solr.solrEnableAuthentication }}"
+            SOLR_ADMIN_USERNAME:
+              value: "{{ .Values.solr.solrUsername }}"
+            SOLR_ADMIN_PASSWORD:
+              secretKeyRef:
+                name: solrcreds
+                key: solr-password
+
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/bash <<'EOF'
+              echo "Executing DB waits..."
+              if [ "$SOLR_ENABLE_AUTHENTICATION" == "yes" ]; then
+                until curl --fail --user "${SOLR_ADMIN_USERNAME}":"${SOLR_ADMIN_PASSWORD}" "${SOLR_HOST}":8983/solr/"${SOLR_CORES}"/admin/ping; do
+                  echo "Solr is not responding... Sleeping 2 seconds..."
+                  sleep 2
+                done
+              else
+                until curl --fail "${SOLR_HOST}":8983/solr/"${SOLR_CORES}"/admin/ping; do
+                  echo "Solr is not responding... Sleeping 2 seconds..."
+                  sleep 2
+                done
+              fi;
+              EOF
+        postgresql-wait:
+          enabled: "{{ if .Values.postgresql.enabled }}true{{ else }}false{{end}}"
+          type: "init"
+          imageSelector: postgresClientImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/sh <<'EOF'
+              echo "Executing DB waits..."
+              {{- $pghost := printf "%v-%v" .Release.Name "postgresql" }}
+              until
+                pg_isready -U {{ .Values.postgresql.postgresqlUsername }} -h {{ $pghost }}
+                do sleep 2
+              done
+              EOF
+        cnpg-wait:
+          enabled: '{{ $result := false }}{{ range .Values.cnpg }}{{ if .enabled }}{{ $result = true }}{{ end }}{{ end }}{{ $result }}'
+          imageSelector: postgresClientImage
+          securityContext:
+            runAsUser: 568
+            runAsGroup: 568
+            readOnlyRootFilesystem: true
+            runAsNonRoot: true
+          resources:
+            inherit: true
+          command:
+            - "/bin/sh"
+            - "-c"
+            - |
+              /bin/sh <<'EOF'
+              {{ range $name, $cnpg := .Values.cnpg }}
+              {{ if $cnpg.enabled }}
+              echo "Executing DB waits..."
+              {{ $cnpgName := include "ix.v1.common.names.fullname" $ }}
+              {{ $nameOverride := $cnpg.nameOverride }}
+              {{ if and (not $cnpg.nameOverride ) (ne $name (include "tc.v1.common.lib.util.cnpg.primary" $)) }}
+                {{ $_ := set $cnpg.nameOverride $name }}
+              {{ end }}
+              {{ if $cnpg.nameOverride }}
+                {{ $cnpgName = printf "%v-%v" $cnpgName $nameOverride }}
+              {{ end }}
+              until
+                pg_isready -U {{ .user }} -h cnpg-{{ $cnpgName }}-rw
+                do sleep 2
+              done
+              until
+                pg_isready -U {{ .user }} -h cnpg-pooler-{{ $cnpgName }}-rw
+                do sleep 2
+              done
+              {{ if $cnpg.acceptRO }}
+              until
+                pg_isready -U {{ .user }} -h cnpg-{{ $cnpgName }}-ro
+                do sleep 2
+              done
+              until
+                pg_isready -U {{ .user }} -h cnpg-pooler-{{ $cnpgName }}-ro
+                do sleep 2
+              done
+              {{ end }}
+              {{ end }}
+              {{ end }}
+              EOF
 
 # TODO:
 portal: {}
