Update common.release.yaml

diff --git a/.github/workflows/common.release.yaml b/.github/workflows/common.release.yaml
--- a/.github/workflows/common.release.yaml
+++ b/.github/workflows/common.release.yaml
@@ -56,25 +56,25 @@ jobs:
         CR_TOKEN: "${{ secrets.BOT_TOKEN }}"
         CR_SKIP_EXISTING: "true"
 
-    - name: Helm | Login
-      shell: bash
-      run: echo ${{ secrets.QUAY_SECRET }} | helm registry login -u ${{ secrets.QUAY_USER }} --password-stdin quay.io
+#    - name: Helm | Login
+#      shell: bash
+#      run: echo ${{ secrets.QUAY_SECRET }} | helm registry login -u ${{ secrets.QUAY_USER }} --password-stdin quay.io
 
 
-    - name: Push Charts to Quay
-      shell: bash
-      run: |
-        for pkg in .cr-release-packages/*.tgz; do
-          if [ -z "${pkg:-}" ]; then
-            break
-          fi
-          filename=$(basename "$pkg")
-          name="${filename%%-[0-9]*.[0-9]*.[0-9]*.tgz}"
-          echo "uploading $name"
-          helm push "${pkg}" oci://quay.io/truecharts || echo "failed to upload $pkg to OCI"
-          curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_TOKEN }}" "https://quay.io/api/v1/repository/truecharts/$name/changevisibility"  || echo "failed to set $pkg to public on OCI"
-        done
+#    - name: Push Charts to Quay
+#      shell: bash
+#      run: |
+ #       for pkg in .cr-release-packages/*.tgz; do
+#          if [ -z "${pkg:-}" ]; then
+ #           break
+ # #        fi
+  #        filename=$(basename "$pkg")
+   #       name="${filename%%-[0-9]*.[0-9]*.[0-9]*.tgz}"
+   #       echo "uploading $name"
+    #      helm push "${pkg}" oci://quay.io/truecharts || echo "failed to upload $pkg to OCI"
+    #      curl -X POST -H "Content-Type: application/json" -d '{"visibility": "public"}' -H "Authorization: Bearer ${{ secrets.QUAY_TOKEN }}" "https://quay.io/api/v1/repository/truecharts/$name/changevisibility"  || echo "failed to set $pkg to public on OCI"
+    #    done
 
-    - name: Helm | Logout
-      shell: bash
-      run: helm registry logout quay.io
+  #  - name: Helm | Logout
+  #    shell: bash
+    #  run: helm registry logout quay.io
